### ISSUE TITLE
CGP46: User picture validation error

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/certigate#46]
If the picture is not uploaded it gives me validation error, while the field not required.

**Comment by ahmedelbougha** [comment]
`SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'photo' cannot be null' in /var/www/vhosts/certigate.camelcasetech.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112
Stack trace:
#0 /var/www/vhosts/certigate.camelcasetech.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /var/www/vhosts/certigate.camelcasetech.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(175): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO use...', Array)
#2 /var/www/vhosts/certigate.camelcasetech.com/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(281): Doctrine\DBAL\Statement->execute()
#3 /var/www/vhosts/certigate.camelcasetech.com/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1018): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->executeInserts()
#4 /var/www/vhosts/certigate.camelcasetech.com/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(378): Doctrine\ORM\UnitOfWork->executeInserts(Object(Doctrine\ORM\Mapping\ClassMetadata))
#5 /var/www/vhosts/certigate.camelcasetech.com/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(356): Doctrine\ORM\UnitOfWork->commit(Object(Users\Entity\User))
#6 /var/www/vhosts/certigate.camelcasetech.com/module/Utilities/src/Utilities/Service/Query/Query.php(235): Doctrine\ORM\EntityManager->flush(Object(Users\Entity\User))
#7 /var/www/vhosts/certigate.camelcasetech.com/module/Users/src/Users/Model/User.php(84): Utilities\Service\Query\Query->save(Object(Users\Entity\User), Array)
#8 /var/www/vhosts/certigate.camelcasetech.com/module/Users/src/Users/Controller/IndexController.php(202): Users\Model\User->saveUser(Array)
#9 /var/www/vhosts/certigate.camelcasetech.com/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractActionController.php(83): Users\Controller\IndexController->newAction()
#10 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#11 /var/www/vhosts/certigate.camelcasetech.com/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#12 /var/www/vhosts/certigate.camelcasetech.com/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#13 /var/www/vhosts/certigate.camelcasetech.com/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractController.php(117): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#14 /var/www/vhosts/certigate.camelcasetech.com/vendor/zendframework/zendframework/library/Zend/Mvc/DispatchListener.php(114): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#15 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#16 /var/www/vhosts/certigate.camelcasetech.com/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#17 /var/www/vhosts/certigate.camelcasetech.com/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#18 /var/www/vhosts/certigate.camelcasetech.com/vendor/zendframework/zendframework/library/Zend/Mvc/Application.php(313): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#19 /var/www/vhosts/certigate.camelcasetech.com/public/index.php(28): Zend\Mvc\Application->run()
#20 {main}`
