### ISSUE TITLE
CGP49: Error while deactivating role

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/certigate#49]
If you created a role then assign it any permission(s), then try to deactivate/delete the role, you shall get this error.

```
exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`certigate`.`acl`, CONSTRAINT `FK_BC806D12D60322AC` FOREIGN KEY (`role_id`) REFERENCES `role` (`id`))' in /var/www/vhosts/certigate.camelcasetech.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91
Stack trace:
#0 /var/www/vhosts/certigate.camelcasetech.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(NULL)
#1 /var/www/vhosts/certigate.camelcasetech.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(987): Doctrine\DBAL\Driver\PDOStatement->execute()
#2 /var/www/vhosts/certigate.camelcasetech.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(595): Doctrine\DBAL\Connection->executeUpdate('DELETE FROM rol...', Array, Array)
#3 /var/www/vhosts/certigate.camelcasetech.com/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(580): Doctrine\DBAL\Connection->delete('role', Array, Array)
#4 /var/www/vhosts/certigate.camelcasetech.com/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1098): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->delete(Object(Users\Entity\Role))
#5 /var/www/vhosts/certigate.camelcasetech.com/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(406): Doctrine\ORM\UnitOfWork->executeDeletions(Object(Doctrine\ORM\Mapping\ClassMetadata))
#6 /var/www/vhosts/certigate.camelcasetech.com/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(356): Doctrine\ORM\UnitOfWork->commit(Object(Users\Entity\Role))
#7 /var/www/vhosts/certigate.camelcasetech.com/module/Utilities/src/Utilities/Service/Query/Query.php(249): Doctrine\ORM\EntityManager->flush(Object(Users\Entity\Role))
#8 /var/www/vhosts/certigate.camelcasetech.com/module/Users/src/Users/Controller/RolesController.php(128): Utilities\Service\Query\Query->remove(Object(Users\Entity\Role))
#9 /var/www/vhosts/certigate.camelcasetech.com/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractActionController.php(83): Users\Controller\RolesController->deleteAction()
#10 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#11 /var/www/vhosts/certigate.camelcasetech.com/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#12 /var/www/vhosts/certigate.camelcasetech.com/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#13 /var/www/vhosts/certigate.camelcasetech.com/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractController.php(117): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#14 /var/www/vhosts/certigate.camelcasetech.com/vendor/zendframework/zendframework/library/Zend/Mvc/DispatchListener.php(114): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#15 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#16 /var/www/vhosts/certigate.camelcasetech.com/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#17 /var/www/vhosts/certigate.camelcasetech.com/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#18 /var/www/vhosts/certigate.camelcasetech.com/vendor/zendframework/zendframework/library/Zend/Mvc/Application.php(313): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#19 /var/www/vhosts/certigate.camelcasetech.com/public/index.php(28): Zend\Mvc\Application->run()
#20 {main}

Next exception 'Doctrine\DBAL\Driver\PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`certigate`.`acl`, CONSTRAINT `FK_BC806D12D60322AC` FOREIGN KEY (`role_id`) REFERENCES `role` (`id`))' in /var/www/vhosts/certigate.camelcasetech.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93
Stack trace:
#0 /var/www/vhosts/certigate.camelcasetech.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(987): Doctrine\DBAL\Driver\PDOStatement->execute()
#1 /var/www/vhosts/certigate.camelcasetech.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(595): Doctrine\DBAL\Connection->executeUpdate('DELETE FROM rol...', Array, Array)
#2 /var/www/vhosts/certigate.camelcasetech.com/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(580): Doctrine\DBAL\Connection->delete('role', Array, Array)
#3 /var/www/vhosts/certigate.camelcasetech.com/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1098): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->delete(Object(Users\Entity\Role))
#4 /var/www/vhosts/certigate.camelcasetech.com/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(406): Doctrine\ORM\UnitOfWork->executeDeletions(Object(Doctrine\ORM\Mapping\ClassMetadata))
#5 /var/www/vhosts/certigate.camelcasetech.com/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(356): Doctrine\ORM\UnitOfWork->commit(Object(Users\Entity\Role))
#6 /var/www/vhosts/certigate.camelcasetech.com/module/Utilities/src/Utilities/Service/Query/Query.php(249): Doctrine\ORM\EntityManager->flush(Object(Users\Entity\Role))
#7 /var/www/vhosts/certigate.camelcasetech.com/module/Users/src/Users/Controller/RolesController.php(128): Utilities\Service\Query\Query->remove(Object(Users\Entity\Role))
#8 /var/www/vhosts/certigate.camelcasetech.com/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractActionController.php(83): Users\Controller\RolesController->deleteAction()
#9 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#10 /var/www/vhosts/certigate.camelcasetech.com/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#11 /var/www/vhosts/certigate.camelcasetech.com/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#12 /var/www/vhosts/certigate.camelcasetech.com/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractController.php(117): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#13 /var/www/vhosts/certigate.camelcasetech.com/vendor/zendframework/zendframework/library/Zend/Mvc/DispatchListener.php(114): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#14 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#15 /var/www/vhosts/certigate.camelcasetech.com/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#16 /var/www/vhosts/certigate.camelcasetech.com/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#17 /var/www/vhosts/certigate.camelcasetech.com/vendor/zendframework/zendframework/library/Zend/Mvc/Application.php(313): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#18 /var/www/vhosts/certigate.camelcasetech.com/public/index.php(28): Zend\Mvc\Application->run()
#19 {main}

Next exception 'Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException' with message 'An exception occurred while executing 'DELETE FROM role WHERE id = ?' with params [10]:

SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`certigate`.`acl`, CONSTRAINT `FK_BC806D12D60322AC` FOREIGN KEY (`role_id`) REFERENCES `role` (`id`))' in /var/www/vhosts/certigate.camelcasetech.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:60
Stack trace:
#0 /var/www/vhosts/certigate.camelcasetech.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /var/www/vhosts/certigate.camelcasetech.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(996): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'DELETE FROM rol...', Array)
#2 /var/www/vhosts/certigate.camelcasetech.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(595): Doctrine\DBAL\Connection->executeUpdate('DELETE FROM rol...', Array, Array)
#3 /var/www/vhosts/certigate.camelcasetech.com/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(580): Doctrine\DBAL\Connection->delete('role', Array, Array)
#4 /var/www/vhosts/certigate.camelcasetech.com/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1098): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->delete(Object(Users\Entity\Role))
#5 /var/www/vhosts/certigate.camelcasetech.com/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(406): Doctrine\ORM\UnitOfWork->executeDeletions(Object(Doctrine\ORM\Mapping\ClassMetadata))
#6 /var/www/vhosts/certigate.camelcasetech.com/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(356): Doctrine\ORM\UnitOfWork->commit(Object(Users\Entity\Role))
#7 /var/www/vhosts/certigate.camelcasetech.com/module/Utilities/src/Utilities/Service/Query/Query.php(249): Doctrine\ORM\EntityManager->flush(Object(Users\Entity\Role))
#8 /var/www/vhosts/certigate.camelcasetech.com/module/Users/src/Users/Controller/RolesController.php(128): Utilities\Service\Query\Query->remove(Object(Users\Entity\Role))
#9 /var/www/vhosts/certigate.camelcasetech.com/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractActionController.php(83): Users\Controller\RolesController->deleteAction()
#10 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#11 /var/www/vhosts/certigate.camelcasetech.com/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#12 /var/www/vhosts/certigate.camelcasetech.com/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#13 /var/www/vhosts/certigate.camelcasetech.com/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractController.php(117): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#14 /var/www/vhosts/certigate.camelcasetech.com/vendor/zendframework/zendframework/library/Zend/Mvc/DispatchListener.php(114): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#15 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#16 /var/www/vhosts/certigate.camelcasetech.com/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#17 /var/www/vhosts/certigate.camelcasetech.com/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#18 /var/www/vhosts/certigate.camelcasetech.com/vendor/zendframework/zendframework/library/Zend/Mvc/Application.php(313): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#19 /var/www/vhosts/certigate.camelcasetech.com/public/index.php(28): Zend\Mvc\Application->run()
#20 {main}
```

**Comment by ahmedelbougha** [comment]
Reviewed, works as expected
